// Mocks generated by Mockito 5.4.4 from annotations
// in half_grade/test/data_layer/repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:half_grade/data_layer/data_sources/local_data_source.dart'
    as _i2;
import 'package:half_grade/data_layer/data_sources/remote_data_source.dart'
    as _i3;
import 'package:half_grade/data_layer/models/quiz_item_model.dart' as _i5;
import 'package:half_grade/data_layer/models/quiz_subject_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock implements _i2.LocalDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [RemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSourceImpl extends _i1.Mock
    implements _i3.RemoteDataSourceImpl {
  MockRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.QuizItemModel>> fetchQuizItems(
          {required String? topic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuizItems,
          [],
          {#topic: topic},
        ),
        returnValue:
            _i4.Future<List<_i5.QuizItemModel>>.value(<_i5.QuizItemModel>[]),
      ) as _i4.Future<List<_i5.QuizItemModel>>);

  @override
  _i4.Future<List<_i6.QuizSubjectModel>> fetchQuizSubjects() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuizSubjects,
          [],
        ),
        returnValue: _i4.Future<List<_i6.QuizSubjectModel>>.value(
            <_i6.QuizSubjectModel>[]),
      ) as _i4.Future<List<_i6.QuizSubjectModel>>);
}
