// Mocks generated by Mockito 5.4.4 from annotations
// in half_grade/test/data_layer/repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:half_grade/core/current_user.dart' as _i6;
import 'package:half_grade/data_layer/data_sources/remote_data_source.dart'
    as _i2;
import 'package:half_grade/data_layer/models/quiz_item_model.dart' as _i5;
import 'package:half_grade/data_layer/models/quiz_subject_model.dart' as _i4;
import 'package:half_grade/domain_layer/entities/user_rank.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSourceImpl extends _i1.Mock
    implements _i2.RemoteDataSourceImpl {
  MockRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.QuizSubjectModel>> fetchQuizSubjects() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuizSubjects,
          [],
        ),
        returnValue: _i3.Future<List<_i4.QuizSubjectModel>>.value(
            <_i4.QuizSubjectModel>[]),
      ) as _i3.Future<List<_i4.QuizSubjectModel>>);

  @override
  _i3.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetPassword({required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {#email: email},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signUp({
    required String? email,
    required String? password,
    required String? username,
    required String? schoolName,
    required String? city,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [],
          {
            #email: email,
            #password: password,
            #username: username,
            #schoolName: schoolName,
            #city: city,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i5.QuizItemModel?> fetchQuizItemById({required int? id}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuizItemById,
          [],
          {#id: id},
        ),
        returnValue: _i3.Future<_i5.QuizItemModel?>.value(),
      ) as _i3.Future<_i5.QuizItemModel?>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchQuizzesMetaData(
          {required String? topic}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchQuizzesMetaData,
          [],
          {#topic: topic},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchCurrentUsersMetadata(
          {required String? uuid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentUsersMetadata,
          [],
          {#uuid: uuid},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> updateCurrentUser({required _i6.CurrentUser? user}) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCurrentUser,
          [],
          {#user: user},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.UserRank>> getRank() => (super.noSuchMethod(
        Invocation.method(
          #getRank,
          [],
        ),
        returnValue: _i3.Future<List<_i7.UserRank>>.value(<_i7.UserRank>[]),
      ) as _i3.Future<List<_i7.UserRank>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getPlayedQuizzesTopics(
          {required List<int>? ids}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlayedQuizzesTopics,
          [],
          {#ids: ids},
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}
